### ISSUE TITLE
Incorrect usage of std::unique_ptr

### ISSUE THREAD

**Issue by ghost** [CaptainCaffeine/chroma#2]
Your Memory object is a unique_ptr in Core::GameBoy, but you proceed to hold raw pointers to it in various other components, passing mem.get(). This defeats the purpose of having a unique_ptr, and you should convert to std::shared_ptr.

**Comment by CaptainCaffeine** [comment]
Thanks for taking the time to make an issue report. This is intentional, and does not defeat the purpose of `unique_ptr`.

You see, the `Memory` object, and all other objects which hold a pointer to it, are owned by the `GameBoy` object. The `GameBoy` object is what determines their lifetimes and manages their resources. Therefore, it initializes and holds `unique_ptr`s to each of them. They could have been regular members, but by making them `unique_ptr`s, I can forward declare them and avoid having to include all of their header files in `GameBoy.h`.

The components of the `GameBoy` have circular references between them. It would be ideal if they could all contain actual references to each other; however, references are non-nullable and all the components must be initialized in some order. So, I chose to make the `Memory` class hold references to the other components, and have the components hold raw pointers to the `Memory` object.

Let's consider what the destructor for `GameBoy` looks like in this setup. The members of a class have to be destroyed in the reverse order in which they are constructed, as the later constructed members may have dependencies on the earlier ones, which is the case here. This currently works fine: `cpu` is destroyed first (which holds a reference to `memory`), then `memory` is destroyed (which holds references to the rest of the components). At this point, the raw pointers in the other components which previously pointed to the `Memory` object are invalidated, but this is fine: they're about to be destroyed anyway. Their lifetime matches that of the `Memory` object they depend on, which is why a raw pointer is safe in this situation. So finally, the rest of the components are destroyed and all other members are swept up, and the GameBoy object itself is destroyed.

Now, what if I had made those `shared_ptr`s instead, and as a consequence used a `shared_ptr` in the `GameBoy` class as well? How would the destructor for `GameBoy` look? Well, the `cpu` object is destroyed as before, but then instead of destroying the `Memory` object, the `shared_ptr` to the `Memory` object held by the `GameBoy` class is destroyed instead, and the reference count for the `Memory` object is decreased by one. Then, as we go on to destroy the `joypad` member, we're stuck. The `Memory` object still exists, and it holds a non-nullable reference to the `Joypad` object. So we cannot destroy the `Joypad` object, or any of the components on which `Memory` depends. I haven't tested it myself, but I'm pretty confident such a program would not compile.

It might work if we swap things around: construct the `Memory` object first, make the rest of the components hold references to the `Memory` object, and have the `Memory` class and `GameBoy` class hold `shared_ptr`s to each of them. However, even if that compiles it would still be incorrect. `shared_ptr` is an *owning* pointer, and `Memory` does not own any of the other objects on which it depends, they are owned solely by the `GameBoy` object. And since the `Memory` object is also owned by the `GameBoy` object, its lifetime is bound to the other components, so we could safely hold raw pointers to the other objects without risk of memory leaks or dangling pointers.
